[package]
name = "terminal-interop-sixel"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
icy_sixel.workspace = true
terminal-interop-core = { path = "../terminal-interop-core" }
terminal-interop-da1 = { path = "../terminal-interop-da1" }

[lints]
workspace = true
